15036 - 04-Feb-20 00:11:27 - ('magento_config', 'http://www.secretchamber.sg/app/etc/local.xml')
15036 - 04-Feb-20 00:11:27 - ('magento_config', 'https://www.secretchamber.sg/app/etc/local.xml')
15036 - 04-Feb-20 00:11:29 - Redirecting http://www.secretchamber.sg/cgi-bin/cgiecho/mgmzbkix -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:34 - Redirecting https://www.secretchamber.sg/cgi-bin/cgiecho/pcjnymoy -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:39 - Redirecting http://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:43 - Redirecting https://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:47 - Redirecting http://www.secretchamber.sg -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:50 - Redirecting https://www.secretchamber.sg -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735B70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047351F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047356F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047357B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047351B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03C6DE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03C55E30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047358B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 08:58:50 - ('magento_config', 'http://www.secretchamber.sg/app/etc/local.xml')
14980 - 04-Feb-20 08:58:50 - ('magento_config', 'https://www.secretchamber.sg/app/etc/local.xml')
14980 - 04-Feb-20 08:58:54 - Redirecting http://www.secretchamber.sg/cgi-bin/cgiecho/epqfzrbg -> https://secretchamber.sg/
14980 - 04-Feb-20 08:59:01 - Redirecting https://www.secretchamber.sg/cgi-bin/cgiecho/cyaayyoi -> https://secretchamber.sg/
14980 - 04-Feb-20 08:59:27 - Redirecting https://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
14980 - 04-Feb-20 08:59:32 - Redirecting http://www.secretchamber.sg -> https://secretchamber.sg/
14980 - 04-Feb-20 08:59:35 - Redirecting https://www.secretchamber.sg -> https://secretchamber.sg/
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762B70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/pojyhxfk
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x007627B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/pojyhxfk
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/pojyhxfk
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x007625B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/yirnwbbv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/yirnwbbv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/yirnwbbv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762330>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/gbkwhpxv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/gbkwhpxv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x007628D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/gbkwhpxv
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x007626D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/knhmyirw
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A3BFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/knhmyirw
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A3B8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/knhmyirw
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00CC1150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00CC10B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00762310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762A70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
14980 - 04-Feb-20 09:00:02 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00762FF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
5706 - 07-Feb-20 09:32:22 - ('magento_config', 'http://www.secretchamber.sg/app/etc/local.xml')
5706 - 07-Feb-20 09:32:22 - ('magento_config', 'https://www.secretchamber.sg/app/etc/local.xml')
5706 - 07-Feb-20 09:32:32 - Redirecting http://www.secretchamber.sg/cgi-bin/cgiecho/vgvjvlfy -> https://secretchamber.sg/
5706 - 07-Feb-20 09:32:38 - Redirecting https://www.secretchamber.sg/cgi-bin/cgiecho/sdrnwdup -> https://secretchamber.sg/
5706 - 07-Feb-20 09:32:43 - Redirecting http://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
5706 - 07-Feb-20 09:32:48 - Redirecting https://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
5706 - 07-Feb-20 09:32:53 - Redirecting http://www.secretchamber.sg -> https://secretchamber.sg/
5706 - 07-Feb-20 09:32:58 - Redirecting https://www.secretchamber.sg -> https://secretchamber.sg/
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fe550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/anmcoqen
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fec10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/anmcoqen
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fe4d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/anmcoqen
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fe690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/tvwppnjh
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f71d610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/tvwppnjh
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fe3d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/tvwppnjh
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6fe910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/gcolckeg
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6fe5d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/gcolckeg
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6febd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-bin/cgiecho/gcolckeg
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6fef10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/punkwsiu
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6feb50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/punkwsiu
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6ee510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /cgi-sys/cgiecho/punkwsiu
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6fec90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6eefd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6eedd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6ee8d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f6ee810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f652a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f710d10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f710a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6ea750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f710ed0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f710190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
5706 - 07-Feb-20 09:33:05 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10f710e90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /
